name: "live_telemetry_gold"
version: "1.0.0"
config-version: 2
profile: "gold"

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  live_telemetry_gold:
    staging:
      +materialized: view
    marts:
      +materialized: table
